"""Ecosystem vegetation + ground-dressing scatter (Agent 3: vegetation / environment art).

Called from export_web.scatter_trees(T, cls). Instead of one uniform density scatter,
vegetation follows southern-Appalachian ecology derived from the terrain and land use:

  * ecology rasters (2.5 m): slope, aspect (sun exposure), topographic position (ridge /
    hollow), D8 flow accumulation -> moisture, distance to water / roads / rail / forest edge
  * canopy trees: dense mixed forest on slopes; oak-hickory + white / Virginia pine on dry
    ridges and south faces; tulip poplar, red maple and hemlock in moist coves and along
    creeks; thin growth and snags on exposed rock
  * irregular forest edges (noise-displaced) with a shrub / sapling / young-pine
    transition belt; understory dogwood, saplings, rhododendron / laurel thickets in
    hollows and on creek banks, laurel on dry rocky ridges
  * farmland partitioned into fields (pasture / hay / plowed / broomsedge fallow) with
    hedgerows + fence-line trees, lone open-grown field oaks, yard trees in towns
  * brush and weeds along road and rail corridors, disturbed ground near infrastructure
  * clear zones: nothing on pavement, shoulders, rail ballast or water (road widths from
    road_types + a per-type maintained clear zone)

Outputs (public/world/, gitignored, regenerated by export_web):
  vegetation_f32.bin  float32 [x_px, y_px, z_m, scale, species_id, seed]  (lib_trees.SPECIES order)
                      seed = autumn * 100 (integer part, 0..100: how far the crown has turned) + hash (fraction)
  props_f32.bin       float32 [x_px, y_px, z_m, scale, kind, rot]         (lib_props.KINDS order)
  eco_u8.bin          uint8 H x W x 10: moisture, disturbed, canopy, field_type, field_angle,
                      hedge, tpi(128=0), talus, road edge dist, rail/bridge edge dist   (terrain material / ground cover drivers)
  eco.json            channel descriptor
Returns the web-compatible trees array [x, y, z, scale, kind(0 hardwood / 1 conifer)].
"""
import os, sys, json, math
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
import numpy as np
import cv2
from scipy import ndimage as ndi
from PIL import Image
from tools.lib.common import path, load_json, W, H

MPP = 2.5
# must match tools/blender/lib_trees.py SPECIES order
SPECIES = ['WhiteOak_A', 'WhiteOak_B', 'Oak_OpenGrown', 'RedMaple_A', 'RedMaple_B', 'TulipPoplar_A', 'TulipPoplar_B',
           'Hickory_A', 'Dogwood', 'Sapling_HW_A', 'Sapling_HW_B', 'WhitePine_A', 'WhitePine_B', 'Hemlock_A', 'Hemlock_B',
           'VirginiaPine', 'Sapling_Pine', 'Snag_A', 'Snag_B', 'Rhododendron_A', 'Laurel_B', 'Brush_A', 'Brush_B',
           'WhiteOak_C', 'RedMaple_C', 'Hemlock_C', 'WhitePine_C', 'Sycamore', 'RiverBirch']
VARIANTS = [('WhiteOak_A', 'WhiteOak_C', 0.4), ('RedMaple_A', 'RedMaple_C', 0.4), ('Hemlock_A', 'Hemlock_C', 0.35), ('WhitePine_A', 'WhitePine_C', 0.4)]
SID = {n: i for i, n in enumerate(SPECIES)}
CONIFERS = {'WhitePine_A', 'WhitePine_B', 'WhitePine_C', 'Hemlock_A', 'Hemlock_B', 'Hemlock_C', 'VirginiaPine', 'Sapling_Pine'}
NOT_WEB = {'Snag_A', 'Snag_B', 'Rhododendron_A', 'Laurel_B', 'Brush_A', 'Brush_B'}
# must match tools/blender/lib_props.py KINDS order
PROPS = ['boulder_large', 'boulder', 'rock_small', 'log', 'log_mossy', 'stump', 'branches', 'roots', 'bark_debris']
PID = {n: i for i, n in enumerate(PROPS)}
# land-use class ids (landuse.json)
WATER, HARD, CONI, FARM, MEADOW, ROCK, RES, COM, IND, RAIL, TOWN = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
FIELD_TYPES = {'none': 0, 'pasture': 1, 'hay': 2, 'plowed': 3, 'fallow': 4, 'lawn': 5}
# clear zone beyond the paved shoulder edge (m): (trees / logs, brush / shrubs).
# = ditch (~2 m) + utility-pole / fence strip (1.5-4 m) + margin (A2 corridor spec); highways keep a
# maintained right-of-way. Ground-cover weeds may still grow up to the verge (lib_groundcover).
CLEAR = {'freeway': (16, 9), 'ramp': (10, 7), 'highway': (11, 7), 'arterial': (7.5, 5.5), 'main_street': (6, 4.5), 'collector': (7.5, 5.5),
         'urban_street': (6, 4.5), 'residential': (6.5, 5), 'rural': (7, 5.5), 'gravel': (6, 5), 'dirt': (5, 4), 'driveway': (4, 3)}
BRIDGE_CLEAR = 8.0   # beyond the deck edge
CLEAR_ZONES = 'data/roads/clear_zones.geojson'   # N: interchange infields etc. (polygons, optional margin_m)


def clear_zone_distance(scale=2):
    """Signed-ish distance (m) outside N's clear-zone polygons minus their margin (<= 0: keep clear), 2x res."""
    Hs, Ws = H * scale, W * scale
    p = path(CLEAR_ZONES)
    if not os.path.exists(p):
        return np.full((Hs, Ws), 1e4, np.float32)
    m = np.zeros((Hs, Ws), np.uint8); marg = np.zeros((Hs, Ws), np.float32)
    feats = load_json(p).get('features', [])
    for f in sorted(feats, key=lambda f: f['properties'].get('margin_m', 3.0) if f.get('properties') else 3.0):
        g = f['geometry']
        polys = [g['coordinates']] if g['type'] == 'Polygon' else g['coordinates'] if g['type'] == 'MultiPolygon' else []
        mg = float((f.get('properties') or {}).get('margin_m', 3.0))
        for poly in polys:
            rings = [(np.asarray(r)[:, :2] * scale).round().astype(np.int32) for r in poly]
            cv2.fillPoly(m, rings[:1], 1); cv2.fillPoly(marg, rings[:1], mg)
            if len(rings) > 1:
                cv2.fillPoly(m, rings[1:], 0)
    if not m.any():
        return np.full((Hs, Ws), 1e4, np.float32)
    d, (iy, ix) = ndi.distance_transform_edt(m == 0, return_indices=True)
    print(f'  clear zones: {len(feats)} polygons from {CLEAR_ZONES}')
    return (d * MPP / scale - marg[iy, ix]).astype(np.float32)


def crag_score(rexp, slope, dwater, T):
    """Where the rock kit builds cliff bands (tools/pipeline/rocks.py) and the canopy stays open:
    exposed crest crags + river-cut gorge walls (steep ground within ~60 m of a channel), concentrated
    into ledges that follow the contours (bedding: a band every ~16 m of height, broken along strike)
    so rocky slopes read as forest with rock ledges, not as bare faces. Crest knobs stay rock."""
    gorge = smoothstep(0.55, 1.0, slope) * np.exp(-dwater / 35.0) * 0.9
    base = np.maximum(smoothstep(0.45, 0.85, rexp) * smoothstep(0.55, 1.1, slope), gorge)
    wob = fbm(T.shape, 10, 991, 2)
    band = smoothstep(0.15, 0.65, np.sin(2 * np.pi * T / 16.0 + 1.2 * wob))
    gaps = smoothstep(-0.6, 0.2, fbm(T.shape, 6, 992, 2))
    knob = smoothstep(0.85, 0.97, rexp) * smoothstep(1.0, 4.0, T - cv2.GaussianBlur(T, (0, 0), 6))   # crest knobs / spur noses
    return base * np.maximum(band * gaps, knob)


def smoothstep(e0, e1, x):
    t = np.clip((x - e0) / (e1 - e0), 0, 1)
    return t * t * (3 - 2 * t)


def fbm(shape, scale_px, seed, octaves=3):
    """Smooth value noise ~N(0,1)-ish at a given feature size (px)."""
    rng = np.random.default_rng(seed)
    h, w = shape
    out = np.zeros(shape, np.float32); amp = 1.0; tot = 0
    for o in range(octaves):
        s = max(1.0, scale_px / (2 ** o))
        n = rng.standard_normal((int(h / s) + 3, int(w / s) + 3)).astype(np.float32)
        n = cv2.resize(n, (int((w / s + 3) * s), int((h / s + 3) * s)), interpolation=cv2.INTER_CUBIC)[:h, :w]
        out += n * amp; tot += amp; amp *= 0.5
    return out / tot * 1.6


# ------------------------------------------------------------------ ecology rasters
def flow_accumulation(T):
    """D8 flow accumulation (cells), processed high -> low."""
    Tp = np.pad(T, 1, mode='edge')
    best = np.zeros_like(T); recv = np.arange(H * W).reshape(H, W)
    ids = np.arange(H * W).reshape(H, W)
    idsp = np.pad(ids, 1, mode='edge')
    for dy in (-1, 0, 1):
        for dx in (-1, 0, 1):
            if dx == 0 and dy == 0:
                continue
            nb = Tp[1 + dy:1 + dy + H, 1 + dx:1 + dx + W]
            drop = (T - nb) / math.hypot(dx, dy)
            m = drop > best
            best[m] = drop[m]
            recv[m] = idsp[1 + dy:1 + dy + H, 1 + dx:1 + dx + W][m]
    order = np.argsort(-T.ravel(), kind='stable')
    acc = np.ones(H * W, np.float64)
    r = recv.ravel()
    for i in order.tolist():
        j = r[i]
        if j != i:
            acc[j] += acc[i]
    return acc.reshape(H, W)


def corridor_edge_distance(features, hw_fn, scale=2):
    """Distance (m) from each 2x-res cell to the nearest corridor EDGE (negative on the corridor),
    plus the (tree, brush) clear zone of that nearest corridor. Returns full-res-2x arrays."""
    Hs, Ws = H * scale, W * scale
    hw = np.zeros((Hs, Ws), np.float32); ct = np.zeros((Hs, Ws), np.float32); cb = np.zeros((Hs, Ws), np.float32)
    lines = []
    for f in features:
        r = hw_fn(f)
        if r is None:
            continue
        lines.append((r[0], r[1], r[2], np.asarray(f['geometry']['coordinates'])[:, :2]))
    lines.sort(key=lambda t: t[0])  # wide roads drawn last (win at junctions)
    cen = np.zeros((Hs, Ws), np.uint8)
    for w, ctree, cbrush, c in lines:
        pts = (c * scale).round().astype(np.int32)
        cv2.polylines(cen, [pts], False, 1, 1)
        cv2.polylines(hw, [pts], False, float(w), 1)
        cv2.polylines(ct, [pts], False, float(ctree), 1)
        cv2.polylines(cb, [pts], False, float(cbrush), 1)
    if not cen.any():
        big = np.full((Hs, Ws), 1e4, np.float32)
        return big, np.zeros_like(big), np.zeros_like(big)
    d, (iy, ix) = ndi.distance_transform_edt(cen == 0, return_indices=True)
    d = d * MPP / scale
    return (d - hw[iy, ix]).astype(np.float32), ct[iy, ix], cb[iy, ix]


def ecology(T, cls):
    gy, gx = np.gradient(cv2.GaussianBlur(T, (0, 0), 1.0), MPP)
    slope = np.hypot(gx, gy)
    # aspect: sun exposure (south / south-west faces are dry and warm in the southern Appalachians)
    # image y grows south: downslope direction = (-gx, -gy); facing south => -gy > 0
    nrm = np.maximum(slope, 1e-6)
    south = (-gy / nrm) * 0.8 + (gx / nrm) * 0.35 * -1  # west component (x grows east)
    sun = np.clip(south * np.clip(slope * 3, 0, 1), -1, 1)
    tpi_s = T - cv2.GaussianBlur(T, (0, 0), 8)     # ~20 m: gullies / spurs
    tpi_l = T - cv2.GaussianBlur(T, (0, 0), 40)    # ~100 m: ridges / coves
    tpi = np.clip(tpi_l / 25 + tpi_s / 6, -1.5, 1.5)
    acc = flow_accumulation(T)
    wet = cls == WATER
    dwater = ndi.distance_transform_edt(~wet) * MPP
    moist = (np.clip((np.log(acc) - 1.5) / 6, 0, 1) * 0.45 + np.clip(-tpi, 0, 1) * 0.35 + np.exp(-dwater / 35) * 0.45
             - np.clip(sun, 0, 1) * 0.2 - np.clip(tpi, 0, 1) * 0.2 + 0.15)
    moist = cv2.GaussianBlur(np.clip(moist, 0, 1).astype(np.float32), (0, 0), 1.2)
    return dict(slope=slope, sun=sun, tpi=tpi, moist=moist, dwater=dwater, acc=acc)


# ------------------------------------------------------------------ fields
def fields(cls, rng, noise):
    """Partition open rural land into fields: returns field-type raster, angle raster, hedge mask."""
    openr = np.isin(cls, [FARM, MEADOW])
    lab, n = ndi.label(openr)
    ftype = np.zeros((H, W), np.uint8); fang = np.zeros((H, W), np.float32)
    # Voronoi subdivision (~120-200 m fields), boundaries wobble a little with noise
    seeds = []
    ys, xs = np.nonzero(openr)
    if len(xs):
        # stable seeds: a fixed jittered grid (~160 m) kept where the land is open, so an edit elsewhere in the
        # land use never reshuffles every field on the map (ids = grid index, types hashed from it)
        sp = math.sqrt(26000 / (MPP * MPP))
        gr = np.random.default_rng(1974)
        gxs, gys = np.meshgrid(np.arange(sp / 2, W, sp), np.arange(sp / 2, H, sp))
        jx = gxs + gr.uniform(-0.4, 0.4, gxs.shape) * sp; jy = gys + gr.uniform(-0.4, 0.4, gys.shape) * sp
        gid = np.arange(gxs.size).reshape(gxs.shape)
        jxi = np.clip(jx.astype(int), 0, W - 1); jyi = np.clip(jy.astype(int), 0, H - 1)
        keep = openr[jyi, jxi]
        seeds = np.stack([jx[keep], jy[keep]], 1).astype(np.float32)
        seed_gid = gid[keep]
        gy_, gx_ = np.mgrid[0:H, 0:W].astype(np.float32)
        wob = noise * 4
        best = np.full((H, W), 1e9, np.float32); cell = np.zeros((H, W), np.int32)
        for k, (sx, sy) in enumerate(seeds):
            x0, x1 = int(max(0, sx - 110)), int(min(W, sx + 110)); y0, y1 = int(max(0, sy - 110)), int(min(H, sy + 110))
            d = np.hypot(gx_[y0:y1, x0:x1] - sx + wob[y0:y1, x0:x1], gy_[y0:y1, x0:x1] - sy - wob[y0:y1, x0:x1])
            m = d < best[y0:y1, x0:x1]
            best[y0:y1, x0:x1][m] = d[m]; cell[y0:y1, x0:x1][m] = seed_gid[k] + 1
        cell[~openr] = 0
        # an isolated small clearing (no seed within reach) is a single field, keyed by its first pixel
        lab_key = np.zeros(n + 1, np.int64)
        first = ndi.minimum(np.arange(H * W).reshape(H, W), lab, index=np.arange(1, n + 1)) if n else []
        lab_key[1:] = np.asarray(first, np.int64) + 10 ** 7
        cid = np.where(cell > 0, cell.astype(np.int64), lab_key[lab])
        uid, inv = np.unique(cid[openr], return_inverse=True)
        hsh = lambda v, k: (np.sin(v * 12.9898 + k * 78.233) * 43758.5453) % 1.0
        tsel = hsh(uid.astype(np.float64), 1.0); ang = hsh(uid.astype(np.float64), 2.0) * math.pi
        # majority class of each field decides the menu
        is_farm = ndi.mean((cls[openr] == FARM).astype(np.float32), labels=inv, index=np.arange(len(uid))) > 0.5
        t_farm = np.select([tsel < 0.55, tsel < 0.75, tsel < 0.85], [FIELD_TYPES['pasture'], FIELD_TYPES['hay'], FIELD_TYPES['plowed']], FIELD_TYPES['fallow'])
        t_mead = np.select([tsel < 0.45], [FIELD_TYPES['pasture']], FIELD_TYPES['fallow'])
        tt = np.where(is_farm, t_farm, t_mead).astype(np.uint8)
        ftype[openr] = tt[inv]; fang[openr] = ang[inv]
        # hedgerows: field-to-field boundaries + open-land boundary (fence lines)
        er = cv2.erode(cid.astype(np.float32), np.ones((3, 3), np.uint8)); dl = cv2.dilate(cid.astype(np.float32), np.ones((3, 3), np.uint8))
        hedge = ((er != dl) & openr)
    else:
        hedge = np.zeros((H, W), bool)
    lawn = np.isin(cls, [RES, TOWN, COM])
    ftype[lawn & (ftype == 0)] = FIELD_TYPES['lawn']
    return ftype, fang, hedge


# ------------------------------------------------------------------ scatter
def _jitter_grid(cell_px, rng, prob):
    gx, gy = np.meshgrid(np.arange(0, W, cell_px), np.arange(0, H, cell_px))
    x = (gx + rng.random(gx.shape) * cell_px).ravel(); y = (gy + rng.random(gy.shape) * cell_px).ravel()
    xi, yi = np.clip(x.astype(int), 0, W - 1), np.clip(y.astype(int), 0, H - 1)
    keep = rng.random(len(x)) < prob[yi, xi]
    return x[keep], y[keep], xi[keep], yi[keep]


def _choose(rng, weights, n=None):
    """weights: dict name -> array(n). Returns species ids."""
    names = list(weights)
    n = n if n is not None else max(np.size(v) for v in weights.values())
    Wm = np.stack([np.broadcast_to(np.maximum(np.asarray(weights[k], np.float64), 0), (n,)) for k in names], 1) + 1e-9
    c = np.cumsum(Wm, 1); c /= c[:, -1:]
    u = rng.random((len(c), 1))
    k = (u > c).sum(1)
    return np.array([SID[names[i]] for i in k], np.int32)


def scatter(T, cls, seed=7):
    rng = np.random.default_rng(seed)
    eco = ecology(T, cls)
    slope, sun, tpi, moist, dwater = eco['slope'], eco['sun'], eco['tpi'], eco['moist'], eco['dwater']
    cr = np.asarray(Image.open(path('data/landuse/conifer_ratio.png')), np.float32) / 255
    wet = cls == WATER
    forest = np.isin(cls, [HARD, CONI])
    rock = cls == ROCK
    # A1: real rock exposure (crags, cut banks, rapids banks) + bank/bed type along channels
    rp = path('data/terrain/rock_exposure_u8.png')
    rexp = cv2.GaussianBlur(np.asarray(Image.open(rp), np.float32) / 255, (0, 0), 0.8) if os.path.exists(rp) else rock.astype(np.float32)
    fxp = path('data/terrain/water_fx_u8.bin')
    btype = np.zeros((H, W), np.float32)
    if os.path.exists(fxp):
        raw = np.fromfile(fxp, np.uint8)
        btype = raw.reshape(raw.size // (H * W), H, W)[3].astype(np.float32) / 255 * 2 - 1   # -1 gravel bar .. +1 rock
    gravelbar = cv2.dilate(np.clip(-btype - 0.2, 0, 1), np.ones((3, 3), np.uint8))
    rock = rock | (rexp > 0.75)
    n40 = fbm((H, W), 16, seed + 1)      # 40 m edge wobble
    n15 = fbm((H, W), 6, seed + 2)       # 15 m
    n100 = fbm((H, W), 40, seed + 3)     # 100 m stand patches
    # signed distance to the forest boundary (m), displaced by noise -> irregular edges
    sd = (ndi.distance_transform_edt(forest) - ndi.distance_transform_edt(~forest)) * MPP
    sdn = sd + n40 * 9 + n15 * 4
    drock = ndi.distance_transform_edt(~rock) * MPP
    # elevation zone (0 valley floors .. 1 high crests), grassy balds, forest openings
    elev = np.clip((T - 330.0) / 210.0, 0, 1)
    from tools.pipeline.landuse import bald_mask
    bald = bald_mask(T)
    n30 = fbm((H, W), 12, seed + 9, 2)   # ~30 m openings
    ridge_r = np.clip(tpi, 0, 1)
    opening = smoothstep(1.15, 1.55, n30 + 0.35 * ridge_r + 0.2 * elev) * forest * (1 - bald)
    # corridors (2x res)
    rt = load_json(path('data/roads/road_types.json'))['types']
    def road_hw(f):
        p = f['properties']
        if p.get('virtual'):
            return None
        c = CLEAR.get(p['type'], (3, 1))
        return (p.get('width_m') or rt[p['type']]['width_m']) / 2 + (p.get('shoulder_m') or 0), c[0], c[1]
    road_d, road_ct, road_cb = corridor_edge_distance(load_json(path('data/roads/roads.geojson'))['features'], road_hw)
    rail_d, _, _ = corridor_edge_distance(load_json(path('data/railways/railways.geojson'))['features'], lambda f: (f['properties']['width_m'] / 2, 6, 3))
    # bridges: keep the deck corridor (and a margin) free, also where the road crosses dry ground
    rds = {f['properties']['id']: f for f in load_json(path('data/roads/roads.geojson'))['features']}
    def bridge_hw(f):
        return (f['properties'].get('deck_width_m') or 10) / 2, 0, 0
    br_feats = [f for f in load_json(path('data/roads/bridges.geojson'))['features'] if f['geometry']['coordinates']]
    bridge_d, _, _ = corridor_edge_distance(br_feats, bridge_hw)
    def min2(a):  # conservative 2x -> 1x (min distance in each 2x2 block)
        return a.reshape(H, 2, W, 2).min(axis=(1, 3))
    cz_d = clear_zone_distance()
    # N's cut / retaining walls: nothing grows on the wall face or right at its crest
    wp = path('data/roads/walls.geojson')
    wall_d, _, _ = corridor_edge_distance(load_json(wp)['features'] if os.path.exists(wp) else [], lambda f: (1.0, 0, 0))
    road1 = min2(road_d); rail1 = min2(rail_d); bridge1 = min2(bridge_d)
    ftype, fang, hedge = fields(cls, rng, n15)
    # balds are one open grass sward: no field partition, no fence rows (broomsedge / oat-grass: 'fallow' look)
    bm = (bald > 0.5) & (cls == MEADOW)
    ftype[bm] = FIELD_TYPES['fallow']; hedge[bald > 0.3] = False

    def sample2(a, x, y):
        return a[np.clip((y * 2).astype(int), 0, H * 2 - 1), np.clip((x * 2).astype(int), 0, W * 2 - 1)]

    def clear_ok(x, y, layer):
        """layer 0 = tree trunk, 1 = brush/shrub."""
        rd = sample2(road_d, x, y); ct = sample2(road_ct, x, y); cb = sample2(road_cb, x, y)
        ra = sample2(rail_d, x, y); bd = sample2(bridge_d, x, y); cz = sample2(cz_d, x, y); wd = sample2(wall_d, x, y)
        xi, yi = np.clip(x.astype(int), 0, W - 1), np.clip(y.astype(int), 0, H - 1)
        dw = dwater[yi, xi]
        if layer == 0:
            return (rd > ct + rng.random(len(x)) * 3) & (ra > 7 + rng.random(len(x)) * 3) & (bd > BRIDGE_CLEAR + 2) & (dw > 3.0) & ~wet[yi, xi] & (cz > 2.0) & (wd > 4.0)
        return (rd > cb + rng.random(len(x)) * 1.0) & (ra > 4.5) & (bd > BRIDGE_CLEAR) & (dw > 1.0) & ~wet[yi, xi] & (cz > 0.0) & (wd > 2.0)

    dev = np.isin(cls, [RES, TOWN])
    pts = []  # (x, y, species, scale)

    # ---- 1) canopy trees
    edge_in = smoothstep(-2, 10, sdn)
    n8 = fbm((H, W), 3.5, seed + 4)
    gaps = np.clip(0.8 + 0.3 * n100 + 0.15 * n15 + 0.12 * n8, 0.3, 1.0)  # small canopy gaps + clumps
    p_can = np.zeros((H, W), np.float32)
    p_can += forest * 0.95 * edge_in * gaps
    p_can = np.maximum(p_can, (sdn > -4) * edge_in * 0.9 * gaps * ~np.isin(cls, [FARM, COM, IND, RAIL]))  # forest tongues
    # painted 'rock' mountainsides: Blue Ridge faces are wooded between the ledges (the rock kit carries the rock)
    p_can[rock] = 0.88 * np.clip(0.7 + 0.3 * n15[rock], 0, 1) * np.where(slope[rock] > 1.1, 0.7, 1.0)
    p_can *= 1 - 0.3 * smoothstep(0.5, 0.95, rexp)   # crags / cut banks: thinner, trees still cling on ledges
    # cliff bands (the rock kit's ledge blocks, tools/pipeline/rocks.py) stay open so the rock reads,
    # and very steep faces only hold scattered trees
    crag = crag_score(rexp, slope, dwater, T)
    p_can *= (1 - 0.8 * crag) * (1 - 0.5 * smoothstep(1.0, 1.6, slope))
    p_can *= 1 - np.clip(gravelbar, 0, 1)    # open gravel bars
    p_can = np.where(dev, np.clip(0.3 + 0.2 * n100 + 0.1 * n15, 0.05, 0.6), p_can)
    p_can[cls == COM] = 0.05; p_can[cls == IND] = 0.03; p_can[cls == RAIL] = 0.0
    p_can[cls == MEADOW] = np.maximum(p_can[cls == MEADOW] * 0.4, 0.008)
    p_can[cls == FARM] = 0.0
    p_can *= np.where(slope > 1.4, 0.75, 1.0)
    p_can *= 1 - 0.88 * opening                      # small openings (old blowdowns / thin soil on the knobs)
    p_can = p_can * (1 - bald) + bald * 0.004         # grassy bald: a few wind-stunted oaks only
    x, y, xi, yi = _jitter_grid(1.75, rng, p_can)
    ok = clear_ok(x, y, 0); x, y, xi, yi = x[ok], y[ok], xi[ok], yi[ok]
    m = moist[yi, xi]; r = np.clip(tpi[yi, xi], -1, 1); s = sun[yi, xi]; c = cr[yi, xi]
    dry = np.clip(0.5 * np.clip(s, 0, 1) + 0.5 * np.clip(r, 0, 1) + 0.4 * (0.5 - m), 0, 1)
    ridge = np.clip(r, 0, 1); cove = np.clip(-r, 0, 1)
    creek = np.exp(-dwater[yi, xi] / 30)
    rk = np.exp(-drock[yi, xi] / 25)
    edge = np.exp(-np.abs(sdn[yi, xi]) / 12) * forest[yi, xi]
    d = dev[yi, xi]
    e = elev[yi, xi]; lowl = 1 - e
    op = opening[yi, xi]; bl = bald[yi, xi]
    # bottomland: sycamore + river birch along streams on valley floors (not in steep ravines)
    bottom = np.exp(-dwater[yi, xi] / 14) * np.clip(1.4 - 1.6 * e, 0, 1) * (1 - smoothstep(0.35, 0.8, slope[yi, xi]))
    # southern Appalachian zonation: chestnut / red oak + hickory on high dry crests, pine on low dry ridges
    # and rock, hemlock + rhododendron coves, tulip poplar + maple moist lower slopes, sycamore / birch on streams
    w = {
        'WhiteOak_A': (0.5 + 1.2 * dry + 0.5 * ridge + 0.6 * e) * (1 - 0.5 * cove) * (1 - d * 0.5),
        'WhiteOak_B': (0.5 + 1.0 * dry + 0.4 * ridge + 0.5 * e) * (1 - 0.5 * cove),
        'Hickory_A': 0.2 + 0.6 * dry + 0.3 * e,
        'RedMaple_A': 0.45 + 0.5 * m + 0.6 * edge + 0.4 * d + 0.2 * e,
        'RedMaple_B': 0.3 + 0.4 * m + 0.8 * edge + 0.5 * d,
        'TulipPoplar_A': (0.12 + 1.8 * m * (1 - ridge)) * (1 - 0.6 * dry) * (1.2 - 0.8 * e),
        'TulipPoplar_B': (0.1 + 1.3 * m * (1 - ridge)) * (1 - 0.5 * dry) * (1.2 - 0.8 * e),
        'Hemlock_A': (0.04 + 2.2 * creek + 0.9 * cove * m) * (0.4 + 1.2 * c) * (1 - d * 0.8) * (1 - 0.5 * bottom),
        'Hemlock_B': (0.03 + 1.6 * creek + 0.6 * cove * m) * (0.4 + 1.2 * c) * (1 - d * 0.8) * (1 - 0.5 * bottom),
        'WhitePine_A': (0.08 + 0.7 * ridge + 0.3 * edge) * (0.3 + 1.8 * c) * (1.15 - 0.5 * e) + 0.15 * d,
        'WhitePine_B': (0.06 + 0.5 * ridge + 0.4 * edge) * (0.3 + 1.6 * c) * (1.15 - 0.5 * e) + 0.1 * d,
        'VirginiaPine': (0.02 + 1.2 * rk + 0.5 * dry * ridge) * (0.5 + c) * (1.2 - 0.6 * e),
        'Oak_OpenGrown': 0.02 + 0.5 * edge * (1 - forest[yi, xi] * 0.5) + 0.5 * d + 3.0 * bl,
        'Dogwood': 0.25 * d,
        'Sycamore': 1.3 * bottom * (1 - ridge) * (1 - 0.5 * d),
        'RiverBirch': 1.1 * bottom * np.exp(-dwater[yi, xi] / 8) * (1 - 0.6 * d),
        # dead standing timber: exposed rock, crests and the edges of openings (old stands)
        'Snag_A': 0.012 + 0.05 * rk + 0.012 * ridge + 0.08 * op,
        'Snag_B': 0.008 + 0.03 * rk + 0.05 * op,
    }
    # stands: each species clumps in ~50-80 m patches (not salt-and-pepper mixing)
    for k_, name in enumerate(w):
        fld = fbm((H, W), 22 + 3 * (k_ % 4), 100 + k_, 2)
        w[name] = np.asarray(w[name]) * np.exp(0.8 * fld[yi, xi])
    sp = _choose(rng, w)
    sc = np.exp(rng.normal(0, 0.14, len(x))) * (1 + 0.12 * cove - 0.12 * ridge - 0.25 * rk * (1 - cove)) * np.where(d, 0.9, 1.0)
    sc *= np.where(slope[yi, xi] > 0.8, 0.9, 1.0) * (1 - 0.1 * e) * (1 - 0.4 * bl)   # shorter, wind-cropped crowns up high
    pts.append((x, y, sp, sc))

    # ---- 2) understory (inside forest): dogwood, saplings, rhododendron/laurel thickets
    # mature forest: fairly open at eye level; understory concentrates in canopy gaps, coves and creek hollows
    p_und = forest * edge_in * (0.07 + 0.13 * np.clip(moist, 0, 1) + 0.35 * np.clip(1 - gaps, 0, 1)) + forest * 0.08 * np.clip(-tpi, 0, 1)
    p_und = (p_und + opening * 0.3) * (1 - 0.8 * crag)    # regrowth in the openings; bare cliff bands
    x, y, xi, yi = _jitter_grid(2.2, rng, p_und.astype(np.float32))
    ok = clear_ok(x, y, 1); x, y, xi, yi = x[ok], y[ok], xi[ok], yi[ok]
    m = moist[yi, xi]; r = np.clip(tpi[yi, xi], -1, 1); creek = np.exp(-dwater[yi, xi] / 25); rk = np.exp(-drock[yi, xi] / 30)
    thicket = np.clip(n15[yi, xi] * 0.7 + 0.3, 0, 1)
    w = {
        'Rhododendron_A': (0.1 + 2.0 * creek + 1.2 * np.clip(-r, 0, 1) * m) * (0.4 + thicket),
        'Laurel_B': (0.1 + 0.9 * np.clip(r, 0, 1) + 0.8 * rk) * (0.4 + thicket),
        'Dogwood': 0.45 * (1 - m * 0.5),
        'Sapling_HW_A': 0.5, 'Sapling_HW_B': 0.4,
        'Sapling_Pine': 0.15 + 0.3 * cr[yi, xi],
        'Brush_B': 0.15,
    }
    sp = _choose(rng, w)
    pts.append((x, y, sp, np.exp(rng.normal(0, 0.18, len(x))) * 0.95))

    # ---- 3) edge transition belt (open side of forest edges): brush, saplings, young pines
    belt = np.exp(-((sdn + 7) / 8) ** 2) * ~forest * ~wet * ~np.isin(cls, [COM, IND, RAIL]) * (1 - 0.6 * dev)
    belt = np.maximum(belt, np.exp(-((sdn - 1) / 4) ** 2) * forest * 0.7)
    x, y, xi, yi = _jitter_grid(1.3, rng, (belt * 0.55).astype(np.float32))
    ok = clear_ok(x, y, 1); x, y, xi, yi = x[ok], y[ok], xi[ok], yi[ok]
    w = {'Brush_A': 1.0, 'Brush_B': 0.9, 'Sapling_HW_A': 0.5, 'Sapling_HW_B': 0.35, 'Sapling_Pine': 0.35 + 0.4 * cr[yi, xi],
         'VirginiaPine': 0.12, 'RedMaple_B': 0.12, 'Dogwood': 0.12}
    sp = _choose(rng, w)
    pts.append((x, y, sp, np.exp(rng.normal(-0.05, 0.2, len(x)))))

    # ---- 4) hedgerows / fence lines between fields (gappy), with fence-line trees
    hd = cv2.dilate(hedge.astype(np.uint8), np.ones((2, 2), np.uint8)) > 0
    hp = hd * np.clip(0.55 + 0.45 * n40, 0, 1) * (n15 > -0.6)
    x, y, xi, yi = _jitter_grid(1.2, rng, (hp * 0.6).astype(np.float32))
    ok = clear_ok(x, y, 1); x, y, xi, yi = x[ok], y[ok], xi[ok], yi[ok]
    w = {'Brush_A': 1.2, 'Brush_B': 1.0, 'Sapling_HW_A': 0.4, 'RedMaple_B': 0.25, 'Oak_OpenGrown': 0.12, 'WhiteOak_B': 0.12,
         'Sapling_Pine': 0.2, 'VirginiaPine': 0.12, 'Hickory_A': 0.06, 'Dogwood': 0.1}
    sp = _choose(rng, w, len(x))
    tree = ~np.isin(sp, [SID['Brush_A'], SID['Brush_B'], SID['Sapling_HW_A'], SID['Sapling_Pine']])
    ok = clear_ok(x, y, 0) | ~tree
    pts.append((x[ok], y[ok], sp[ok], np.exp(rng.normal(-0.05, 0.18, ok.sum()))))

    # ---- 5) lone open-grown trees in pastures / meadows + yard trees
    lone = (np.isin(ftype, [FIELD_TYPES['pasture'], FIELD_TYPES['fallow']]) * 0.0035 + (cls == MEADOW) * 0.006) * (1 - 0.8 * bald)
    x, y, xi, yi = _jitter_grid(2.0, rng, lone.astype(np.float32))
    ok = clear_ok(x, y, 0); x, y = x[ok], y[ok]
    sp = _choose(rng, {'Oak_OpenGrown': np.full(len(x), 1.0), 'RedMaple_A': np.full(len(x), 0.25), 'WhitePine_A': np.full(len(x), 0.15), 'Hickory_A': np.full(len(x), 0.1)})
    pts.append((x, y, sp, np.exp(rng.normal(0.05, 0.15, len(x)))))

    # ---- 6) roadside / railside brush & weeds (outside the mowed clear zone, open land)
    rs = (np.exp(-np.clip(road1 - 3, 0, None) / 4) * (road1 > 1) + np.exp(-np.clip(rail1 - 3, 0, None) / 4) * (rail1 > 2)) \
        * ~wet * np.isin(cls, [MEADOW, FARM, HARD, CONI, ROCK, RES]) * np.clip(0.4 + 0.6 * n15, 0, 1)
    x, y, xi, yi = _jitter_grid(1.4, rng, (rs * 0.35).astype(np.float32))
    ok = clear_ok(x, y, 1); x, y = x[ok], y[ok]
    sp = _choose(rng, {'Brush_A': np.full(len(x), 1.0), 'Brush_B': np.full(len(x), 1.3), 'Sapling_HW_A': np.full(len(x), 0.25), 'Sapling_Pine': np.full(len(x), 0.15)})
    pts.append((x, y, sp, np.exp(rng.normal(-0.1, 0.2, len(x)))))

    # ---- 7) creek-bank thickets (dense near water, outside the channel)
    bank = np.exp(-((dwater - 5) / 5) ** 2) * ~wet * ~np.isin(cls, [COM, IND, RAIL, FARM]) * (1 - 0.7 * dev) * (1 - np.clip(gravelbar, 0, 1)) * (1 - 0.7 * np.clip(rexp, 0, 1))
    x, y, xi, yi = _jitter_grid(1.4, rng, (bank * 0.4).astype(np.float32))
    ok = clear_ok(x, y, 1); x, y = x[ok], y[ok]
    lowb = np.clip(1.4 - 1.6 * elev[np.clip(y.astype(int), 0, H - 1), np.clip(x.astype(int), 0, W - 1)], 0, 1)
    sp = _choose(rng, {'Rhododendron_A': np.full(len(x), 1.0) * (1.2 - 0.6 * lowb), 'Laurel_B': np.full(len(x), 0.5), 'Brush_A': np.full(len(x), 0.8),
                       'RedMaple_B': np.full(len(x), 0.25), 'Sapling_HW_B': np.full(len(x), 0.3), 'Hemlock_B': np.full(len(x), 0.2) * (1.2 - 0.6 * lowb),
                       'RiverBirch': 0.35 * lowb})
    pts.append((x, y, sp, np.exp(rng.normal(0, 0.18, len(x)))))

    # ---- 8) yard shrubs / foundation plantings / overgrown lot corners in town
    ys_ = dev * np.clip(0.5 + 0.5 * n15, 0, 1) * 0.12 + (cls == COM) * 0.03
    x, y, xi, yi = _jitter_grid(1.3, rng, ys_.astype(np.float32))
    ok = clear_ok(x, y, 1); x, y = x[ok], y[ok]
    sp = _choose(rng, {'Brush_B': 1.0, 'Laurel_B': 0.8, 'Brush_A': 0.5, 'Dogwood': 0.25, 'Sapling_Pine': 0.15}, len(x))
    pts.append((x, y, sp, np.exp(rng.normal(-0.1, 0.18, len(x)))))

    X = np.concatenate([p[0] for p in pts]); Y = np.concatenate([p[1] for p in pts])
    S = np.concatenate([p[2] for p in pts]).astype(np.int32); SC = np.concatenate([p[3] for p in pts]).astype(np.float32)
    for a, b, frac in VARIANTS:  # spread the most common species over more meshes (less visible repetition)
        sel = (S == SID[a]) & (rng.random(len(S)) < frac)
        S[sel] = SID[b]
    xi, yi = np.clip(X.astype(int), 0, W - 1), np.clip(Y.astype(int), 0, H - 1)
    Z = T[yi, xi]
    # autumn progress per crown: colour comes first up high, on warm south / south-west faces, on ridges and
    # sunny forest edges; moist coves and creek bottoms stay green; whole stands turn together (~75 m patches)
    n75 = fbm((H, W), 30, seed + 11, 2)
    # forest edges and open-grown trees colour first (full sun: maples / sourwood / sumac edges blaze red-orange)
    edge_sun = np.exp(-np.abs(sdn) / 15) + 0.6 * ~forest
    aut = (0.34 + 0.45 * elev + 0.25 * np.clip(sun, 0, 1) - 0.1 * np.clip(-sun, 0, 1) + 0.1 * np.clip(tpi, 0, 1)
           - 0.25 * np.clip(-tpi, 0, 1) * moist - 0.15 * np.exp(-dwater / 25) + 0.35 * np.clip(edge_sun, 0, 1) + 0.14 * n75)
    aut = np.clip(aut[yi, xi] + rng.normal(0, 0.06, len(X)), 0, 1)
    seed_col = np.round(aut * 100) + rng.random(len(X)) * 0.999
    veg = np.stack([X, Y, Z, SC, S.astype(np.float32), seed_col], 1).astype(np.float32)

    # ---- canopy cover raster from the actual trees (terrain: forest floor under trees)
    big = ~np.isin(S, [SID[n] for n in NOT_WEB | {'Sapling_HW_A', 'Sapling_Pine', 'Dogwood'}])
    cov = np.zeros((H, W), np.float32)
    np.add.at(cov, (yi[big], xi[big]), 1.0)
    cov = np.clip(cv2.GaussianBlur(cov, (0, 0), 2.2) * 9, 0, 1)

    props = scatter_props(rng, T, cls, eco, forest, sdn, rock, drock, road1, rail1, wet, n15, clear_ok, opening)
    # ---- eco raster
    disturbed = np.clip(np.exp(-np.clip(road1, 0, None) / 6) * 0.8 + np.exp(-np.clip(rail1, 0, None) / 8) + np.isin(cls, [IND, RAIL]) * 0.8
                        + (cls == COM) * 0.35, 0, 1)
    talus = np.clip(np.exp(-drock / 10) * smoothstep(0.35, 0.7, slope) * 0.8 + gravelbar * 0.8, 0, 1)
    eco_u8 = np.stack([
        moist, disturbed, cov, ftype.astype(np.float32) / 255, fang / math.pi, hedge.astype(np.float32),
        np.clip(tpi / 3 + 0.5, 0, 1), talus,
        # corridor edge distances (m / 25.5, 0.1 m steps): ground cover keeps pavement, ballast and bridge decks clear
        np.clip(road1, 0, 25.5) / 25.5, np.clip(np.minimum(rail1, bridge1), 0, 25.5) / 25.5, np.clip(rexp, 0, 1),
        np.clip(dwater, 0, 25.5) / 25.5], -1)
    eco_u8 = (np.clip(eco_u8, 0, 1) * 255).round().astype(np.uint8)
    eco_u8[..., 3] = ftype
    return veg, props, eco_u8


def scatter_props(rng, T, cls, eco, forest, sdn, rock, drock, road1, rail1, wet, n15, clear_ok, opening=0.0):
    slope, dwater, moist, tpi = eco['slope'], eco['dwater'], eco['moist'], eco['tpi']
    out = []
    def add(prob, cell, kinds, scale_mu, scale_sd, layer=0, allow_water=False):
        x, y, xi, yi = _jitter_grid(cell, rng, np.clip(prob, 0, 1).astype(np.float32))
        if not allow_water:
            ok = clear_ok(x, y, layer); x, y, xi, yi = x[ok], y[ok], xi[ok], yi[ok]
        else:
            ok = (road1[yi, xi] > 2) & (rail1[yi, xi] > 2); x, y, xi, yi = x[ok], y[ok], xi[ok], yi[ok]
        names = list(kinds); p = np.array([kinds[n] for n in names], float); p /= p.sum()
        k = rng.choice(len(names), len(x), p=p)
        kid = np.array([PID[names[i]] for i in k])
        out.append(np.stack([x, y, T[yi, xi], np.exp(rng.normal(scale_mu, scale_sd, len(x))), kid, rng.random(len(x)) * 6.283], 1))
    # dry upper-bank rocks (in-channel / waterline boulders are placed by A1's lib_water)
    steepbank = smoothstep(0.1, 0.5, slope)
    bank = np.exp(-((dwater - 7) / 5) ** 2) * ~wet * (0.3 + 0.7 * steepbank)
    add(bank * np.clip(0.5 + 0.5 * n15, 0, 1) * 0.25, 1.6, {'boulder': 1.0, 'rock_small': 1.5}, -0.1, 0.3)
    # talus below cliffs / rock outcrops, scattered rock on steep ground
    tal = np.exp(-drock / 15) * smoothstep(0.2, 0.55, slope) * ~rock + rock * 0.25
    add(tal * 0.6, 1.5, {'boulder_large': 0.5, 'boulder': 1.0, 'rock_small': 0.8}, 0.1, 0.35)
    # sparse forest-floor boulders (more on ridges / steep)
    add(forest * (0.012 + 0.04 * smoothstep(0.4, 0.9, slope) + 0.02 * np.clip(tpi, 0, 1)), 2.0, {'boulder': 1.0, 'rock_small': 1.5}, -0.1, 0.3)
    # fallen logs / branches / debris on the forest floor (more in moist hollows)
    ff = forest * smoothstep(0, 8, sdn) * (0.05 + 0.08 * moist) + opening * 0.12
    add(ff, 2.4, {'log': 1.0, 'log_mossy': 0.8, 'branches': 1.6}, 0.0, 0.2)   # bark_debris dropped: a square patch that reads as a decal
    # creek debris: logs, roots along creek banks
    add(np.exp(-dwater / 6) * ~wet * forest * 0.12, 1.6, {'log_mossy': 1.0, 'roots': 1.0, 'branches': 0.6}, 0.0, 0.2)
    # stumps: logging near forest edges, roads, fields
    add(np.exp(-np.abs(sdn) / 15) * 0.03 + forest * np.exp(-np.clip(road1, 0, None) / 25) * 0.02, 2.4, {'stump': 1.0}, 0.0, 0.2)
    if not out:
        return np.zeros((0, 6), np.float32)
    return np.concatenate(out).astype(np.float32)


def run(T, cls):
    veg, props, eco = scatter(T, cls)
    out = path('public/world')
    os.makedirs(out, exist_ok=True)
    veg.astype('<f4').tofile(os.path.join(out, 'vegetation_f32.bin'))
    props.astype('<f4').tofile(os.path.join(out, 'props_f32.bin'))
    eco.tofile(os.path.join(out, 'eco_u8.bin'))
    with open(os.path.join(out, 'eco.json'), 'w') as f:
        json.dump({'w': W, 'h': H, 'channels': ['moisture', 'disturbed', 'canopy', 'field_type', 'field_angle', 'hedge', 'tpi', 'talus', 'road_edge_m/25.5', 'rail_bridge_edge_m/25.5', 'rock_exposure', 'water_dist_m/25.5'],
                   'field_types': FIELD_TYPES, 'species': SPECIES, 'props': PROPS,
                   'vegetation': {'file': 'vegetation_f32.bin', 'stride': 6, 'count': int(len(veg)), 'seed': 'autumn*100 + hash fraction'},
                   'props_file': {'file': 'props_f32.bin', 'stride': 6, 'count': int(len(props))}}, f, indent=1)
    s = veg[:, 4].astype(int)
    web = ~np.isin(s, [SID[n] for n in NOT_WEB])
    kind = np.isin(s, [SID[n] for n in CONIFERS]).astype(np.float32)
    trees = np.stack([veg[:, 0], veg[:, 1], veg[:, 2], np.clip(veg[:, 3], 0.5, 1.5), kind], 1)[web]
    from collections import Counter
    cnt = Counter(SPECIES[i] for i in s)
    print(f'vegetation: {len(veg)} plants ({web.sum()} trees for web), {len(props)} props')
    print('  ' + ', '.join(f'{k} {v}' for k, v in sorted(cnt.items(), key=lambda t: -t[1])))
    return trees.astype(np.float32)


if __name__ == '__main__':
    T = np.fromfile(path('data/terrain/height_graded_f32.bin'), np.float32).reshape(H, W)
    cls = np.array(Image.open(path('data/landuse/landuse_classes.png')))
    trees = run(T, cls)
    trees.astype('<f4').tofile(path('public/world/trees.bin'))
